// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLO_1j3z3loucXkYL59mpJU9hqFmxLeEk',
    appId: '1:231488523510:web:0b35592063b4a534dcb0d7',
    messagingSenderId: '231488523510',
    projectId: 'flutter-ecommerce-app-78460',
    authDomain: 'flutter-ecommerce-app-78460.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-78460.firebasestorage.app',
    measurementId: 'G-R0MBFL0NTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASR9IRfOqhKcHPr0LtTc0s4lz2IESiQv8',
    appId: '1:231488523510:android:5fe856a26429fb03dcb0d7',
    messagingSenderId: '231488523510',
    projectId: 'flutter-ecommerce-app-78460',
    storageBucket: 'flutter-ecommerce-app-78460.firebasestorage.app',
  );
}
